# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nevin/Documents/CodingProjects/Quant/LowLatencyTradingSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nevin/Documents/CodingProjects/Quant/LowLatencyTradingSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nevin/Documents/CodingProjects/Quant/LowLatencyTradingSystem/CMakeFiles /home/nevin/Documents/CodingProjects/Quant/LowLatencyTradingSystem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nevin/Documents/CodingProjects/Quant/LowLatencyTradingSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libcommon

# Build rule for target.
libcommon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcommon
.PHONY : libcommon

# fast build rule for target.
libcommon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/build
.PHONY : libcommon/fast

#=============================================================================
# Target rules for targets named thread_example

# Build rule for target.
thread_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thread_example
.PHONY : thread_example

# fast build rule for target.
thread_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_example.dir/build.make CMakeFiles/thread_example.dir/build
.PHONY : thread_example/fast

#=============================================================================
# Target rules for targets named mem_pool_example

# Build rule for target.
mem_pool_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mem_pool_example
.PHONY : mem_pool_example

# fast build rule for target.
mem_pool_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mem_pool_example.dir/build.make CMakeFiles/mem_pool_example.dir/build
.PHONY : mem_pool_example/fast

#=============================================================================
# Target rules for targets named lf_queue_example

# Build rule for target.
lf_queue_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lf_queue_example
.PHONY : lf_queue_example

# fast build rule for target.
lf_queue_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lf_queue_example.dir/build.make CMakeFiles/lf_queue_example.dir/build
.PHONY : lf_queue_example/fast

#=============================================================================
# Target rules for targets named logging_example

# Build rule for target.
logging_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logging_example
.PHONY : logging_example

# fast build rule for target.
logging_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging_example.dir/build.make CMakeFiles/logging_example.dir/build
.PHONY : logging_example/fast

lf_queue_example.o: lf_queue_example.cpp.o
.PHONY : lf_queue_example.o

# target to build an object file
lf_queue_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/lf_queue_example.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lf_queue_example.dir/build.make CMakeFiles/lf_queue_example.dir/lf_queue_example.cpp.o
.PHONY : lf_queue_example.cpp.o

lf_queue_example.i: lf_queue_example.cpp.i
.PHONY : lf_queue_example.i

# target to preprocess a source file
lf_queue_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/lf_queue_example.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lf_queue_example.dir/build.make CMakeFiles/lf_queue_example.dir/lf_queue_example.cpp.i
.PHONY : lf_queue_example.cpp.i

lf_queue_example.s: lf_queue_example.cpp.s
.PHONY : lf_queue_example.s

# target to generate assembly for a file
lf_queue_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/lf_queue_example.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lf_queue_example.dir/build.make CMakeFiles/lf_queue_example.dir/lf_queue_example.cpp.s
.PHONY : lf_queue_example.cpp.s

logging_example.o: logging_example.cpp.o
.PHONY : logging_example.o

# target to build an object file
logging_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/logging_example.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging_example.dir/build.make CMakeFiles/logging_example.dir/logging_example.cpp.o
.PHONY : logging_example.cpp.o

logging_example.i: logging_example.cpp.i
.PHONY : logging_example.i

# target to preprocess a source file
logging_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/logging_example.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging_example.dir/build.make CMakeFiles/logging_example.dir/logging_example.cpp.i
.PHONY : logging_example.cpp.i

logging_example.s: logging_example.cpp.s
.PHONY : logging_example.s

# target to generate assembly for a file
logging_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/logging_example.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging_example.dir/build.make CMakeFiles/logging_example.dir/logging_example.cpp.s
.PHONY : logging_example.cpp.s

mem_pool_example.o: mem_pool_example.cpp.o
.PHONY : mem_pool_example.o

# target to build an object file
mem_pool_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/mem_pool_example.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mem_pool_example.dir/build.make CMakeFiles/mem_pool_example.dir/mem_pool_example.cpp.o
.PHONY : mem_pool_example.cpp.o

mem_pool_example.i: mem_pool_example.cpp.i
.PHONY : mem_pool_example.i

# target to preprocess a source file
mem_pool_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/mem_pool_example.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mem_pool_example.dir/build.make CMakeFiles/mem_pool_example.dir/mem_pool_example.cpp.i
.PHONY : mem_pool_example.cpp.i

mem_pool_example.s: mem_pool_example.cpp.s
.PHONY : mem_pool_example.s

# target to generate assembly for a file
mem_pool_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/mem_pool_example.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mem_pool_example.dir/build.make CMakeFiles/mem_pool_example.dir/mem_pool_example.cpp.s
.PHONY : mem_pool_example.cpp.s

thread_example.o: thread_example.cpp.o
.PHONY : thread_example.o

# target to build an object file
thread_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/thread_example.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_example.dir/build.make CMakeFiles/thread_example.dir/thread_example.cpp.o
.PHONY : thread_example.cpp.o

thread_example.i: thread_example.cpp.i
.PHONY : thread_example.i

# target to preprocess a source file
thread_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/thread_example.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_example.dir/build.make CMakeFiles/thread_example.dir/thread_example.cpp.i
.PHONY : thread_example.cpp.i

thread_example.s: thread_example.cpp.s
.PHONY : thread_example.s

# target to generate assembly for a file
thread_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcommon.dir/build.make CMakeFiles/libcommon.dir/thread_example.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_example.dir/build.make CMakeFiles/thread_example.dir/thread_example.cpp.s
.PHONY : thread_example.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lf_queue_example"
	@echo "... libcommon"
	@echo "... logging_example"
	@echo "... mem_pool_example"
	@echo "... thread_example"
	@echo "... lf_queue_example.o"
	@echo "... lf_queue_example.i"
	@echo "... lf_queue_example.s"
	@echo "... logging_example.o"
	@echo "... logging_example.i"
	@echo "... logging_example.s"
	@echo "... mem_pool_example.o"
	@echo "... mem_pool_example.i"
	@echo "... mem_pool_example.s"
	@echo "... thread_example.o"
	@echo "... thread_example.i"
	@echo "... thread_example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

